
keycloak:
    replicas: 2

    service:
        type: NodePort
        httpNodePort: ${NODE_PORT_KEYCLOAK}
        # needs to be same pls do not change
        httpPort: ${NODE_PORT_KEYCLOAK}

    ingress:
        enabled: false

    persistence:
        # The database vendor. Can be either "postgres", "mysql", "mariadb", or "h2"
        dbVendor: mysql

    extraEnv: |
        - name: JDBC_PARAMS
          value: useSSL=false
